# fly.toml app configuration file generated for abc-music on 2024-07-05T17:00:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'abc-music'
primary_region = 'ams'

[build]

[env]
  DATABASE_URL = 'sqlite:/litefs/production.sqlite'
  HOST = '0.0.0.0'
  SITE_URL = 'https://abc-music.fly.dev/'

[[mounts]]
  source = 'litefs'
  destination = '/var/lib/litefs'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
