# fly.toml app configuration file generated for abc-music on 2024-06-20T13:40:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'abc-music'
primary_region = 'ams'

[build]

[env]
  HOST = '0.0.0.0'
  SITE_URL = 'https://abc-music.fly.dev/'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
